### ISSUE TITLE
Error redirect Kirim Project

### ISSUE THREAD

**Issue by lasarasati** [siapbantu/siapbantu.website#11]
Untuk pengguna yang belum mendaftar ketika mengklik tombol "Kirim Project" akan autor redirect ke halaman Error 505

**Comment by shitiomatic** [comment]
Waduh nggak notice tadi

**Comment by shitiomatic** [comment]
Yang rusak cuma pas di production, di lokal kagak

**Comment by shitiomatic** [comment]
@lasarasati coba test lagi!

**Comment by lasarasati** [comment]
Fixed
