### ISSUE TITLE
Invalid link in readme for contributing guidelines

### ISSUE THREAD

**Issue by ahmad-reza619** [siapbantu/siapbantu.website#9]
Hi there great people 👋 

I just wanted to inform you guys, that the link to Contributing Guidelines in Readme file is incorrect. this should be a fairly easy fix. i know it's not done yet, but a little maintenance doesn't hurt 😄 . Should i open up PR for this small fix ? 🤔

**Comment by lasarasati** [comment]
Thank banget udah di notice, soalnya project ini belum layak tayang. Sepertinya nggak perlu submit PR :smile:

**Comment by lasarasati** [comment]
Dan semua datanya masih dummy @shitiomatic

**Comment by shitiomatic** [comment]
@lasarasati #10
